version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - cmd/market-vibranium/.env
    depends_on:
      - redis
      - dynamodb
    command: sh -c "while ! nc -z redis 6379; do sleep 1; done && while ! nc -z dynamodb 8000; do sleep 1; done && go run init_dynamodb.go && /market-vibranium"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
