version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/market-vibranium/.env
    command: sh -c "/market-vibranium"
    volumes:
      - my-snapshots-volume:/app/snapshots
    networks:
      - localNetwork
#    deploy:
#      resources:
#        limits:
#          cpus: "12"
#          memory: 24G
#        reservations:
#          cpus: "8"
#          memory: 16G

#  db:
#    image: mysql:8.4.0
#    restart: always
#    env_file:
#      - cmd/market-vibranium/.env
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#    volumes:
#      - my-db:/var/lib/mysql
#      - ./cmd/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
#    command: >
#      --server-id=1
#      --log-bin=master-bin
#      --binlog-format=ROW
#      --innodb_flush_log_at_trx_commit=1
#      --sync_binlog=1
#      --max_connections=10000
#      --innodb_buffer_pool_size=24G
#    networks:
#      - localNetwork

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - localNetwork

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/dashboards_json:/var/lib/grafana/dashboards
    networks:
      - localNetwork

#  k6:
#    image: grafana/k6
#    volumes:
#      - ./config/k6:/scripts
#    depends_on:
#      - app
#    command: run /scripts/test-script.js
#    networks:
#      - localNetwork

networks:
  localNetwork:
    driver: bridge

volumes:
  grafana-storage:
  my-snapshots-volume: