version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - cmd/market-vibranium/.env
    depends_on:
      - localstack
      - sqs-creator
    command: sh -c "go run infra/local/init_dynamodb.go && /market-vibranium"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4575:4575"
    environment:
      - SERVICES=sqs,dynamodb,s3
      - DEBUG=1

  sqs-creator:
    image: amazon/aws-cli
    depends_on:
      - localstack
    entrypoint: >
      sh -c "
        until curl -s http://localstack:4566/health; do
          echo waiting for localstack;
          sleep 5;
        done;
        aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name order-queue.fifo --attributes FifoQueue=true,ContentBasedDeduplication=true --region us-east-1 --no-sign-request
      "